name: Windows

on:
  push:
  pull_request:
  schedule:
    - cron: "35 2 * * *"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run cargo-vcpkg integration tests
        shell: bash
        run: wstest/run.sh
